### ISSUE TITLE
Overview 8/10

### ISSUE THREAD

**Issue by ChristianLind** [xNoga/groupB1-blog#1]
Der er en god rød tråd igennem bloggen, kan godt lide jeres opdeling af teori, arbejde og fremtidigt arbejde.
Det er bare ærgerligt at i mangler referencer til jeres kildehenvisning. 
Igennem bloggen mangler der noget der viser hvornår i bruger jeres kilder eller hvordan i bruger dem… Fx. i “hvorfor er manglende sikkerhed et problem”, har i hvad jeg gætter på er et citat fra en kilde men der står ikke hvilken kilde det er. 

Der er også et par gentagelser hist og her men ikke noget slemt, den værste er nok:
“Da vi heller ikke have sat en firewall op, der bremsede udefrakommende forbindelser på den port er det ikke underligt, at det gik galt.”
4 linjer efter skrives der:
“Yderligere havde vi ikke sat authentication op på databasen ligesom vi heller ikke havde taget højde for, at vores firewall ikke blokerede ukendt udefrakommende trafik på vores MongoDB-port.”

**Comment by xNoga** [comment]
"Hvorfor er manglende sikkerhed et problem?" er som sådan ikke taget noget sted fra, men bare en opsummering af de kilder vi har læst. Vi forstår skam kritikken og bruger nu links de steder, hvor vi direkte har brugt kilder. Vi har ikke tænkt os at markere teksten med små tal som man ville gøre i en rapport, men håber af vi ved hjælp af inline-links kan give et overblik af hvornår vi bruger kilderne.
