### ISSUE TITLE
Design constraints and assumptions 10/10

### ISSUE THREAD

**Issue by ChristianLind** [xNoga/groupB1-blog#3]
I kommer med gode grunde for hvorfor MongoDB ikke er sikkert, personlige erfaringer er et plus.
I kommer med op til flere løsninger til hvordan sikkerheden i MongoDB kan forbedres.
Jeres antagelser er begrundet meget godt.

**Comment by xNoga** [comment]
Vi antager at der ikke skal ændres noget.
