### ISSUE TITLE
Theoretical explanations 7/10

### ISSUE THREAD

**Issue by ChristianLind** [xNoga/groupB1-blog#4]
I kommer godt ind over hvad der kan ske hvis en bot scanner jeres netværk, og omkring grunden til hvad det leder til. 
Jeres forklaring omkring problematikken med sikkerhed i mongoDB’s manglende “out of the box” sikkerheds konfiguration mangler lidt, ja i har skrevet hvor MongoDB er usikker, men ikke om hvorfor der ikke er nogen. 
Det kunne have være godt med en sektion der udbyder grundene.

**Comment by xNoga** [comment]
Jeg mener egentlig vi svarer ret godt på det i det afsnit, hvor vi netop pointerer, at MongoDB er en open-source database, og at den derfor kommer meget lightweight out of the box. Og at man derfor som udvikler selv er nødt til at konfigurere sikkerheden på databasen. Jeg tror ikke der som sådan er en grund, jeg tror bare det er fordi MongoDB er open-source og at man derfor selv har valget om at konfigurerer sikkerhed eller ej. Hvis man vælger at betale for MongoDB's Enterprise version er der mere sikkerhed sat op ved installation. Den manglende opsætning i gratis versionen kan måske ses som en forretningsmodel til at få folk til at købe Enterprise-versionen.
