### ISSUE TITLE
Design criteria, sample calculations and simulations 6/10

### ISSUE THREAD

**Issue by ChristianLind** [xNoga/groupB1-blog#5]
I forklarer om en del løsninger til at forbedre sikkerheden af MongoDB, det er også helt fint at i kommer med eksempler som firewall, authentication og default porte. I har vist hvordan firewall’en ser ud efter den er sat op. 
Det kunne bare være fedt hvis i viste hvordan man satte den op. 
Selvom I ikke har fået authentication eller ændret porten kunne det også være en mulighed at vise hvordan man bar sig ad med at gøre det.

**Comment by xNoga** [comment]
Mht firewall så giver vi jer ret. Men vi mener også at det er et blog-indlæg og ikke en tutorial. Vi har derfor linket til en tutorial mht opsætning af firewalls på en Ubuntu-server. Authentication og port-ændring kan ses i den Security Checklist, som vi allerede har linket til.
