### ISSUE TITLE
Previous work / Future work 10/10

### ISSUE THREAD

**Issue by ChristianLind** [xNoga/groupB1-blog#6]
I kommer med en god gennemgang over jeres manglende sikkerhed i starten af projektet, i kom godt igennem konsekvenserne og hvorfor at en firewall til at beskytte jeres testdata var nødvendig.
Dernæst giver i op til flere eksempler på hvad i stadig kan overveje, for at “brugerne” kan føle sig sikre på at deres data ikke har mulighed for at blive hacket. 
Dette kan ses ved jeres overvejelse om at komme helt væk fra MongoDB's default porte og authentication.

**Comment by xNoga** [comment]
Vi antager at der ikke skal ændres noget her. Tak for al jeres konstruktive kritik! 👍
